# Guidelines for contributors for the "Guiding Principles" chapter {#appendix_principles_contribute}

__1. Focus on high-level principles.__ Do not include recommendations or discussions about statistical methods and procedures such as "should we correct for multiple comparisons" or "should we remove outliers" or "is bayesian better". These issues will be discussed in separate FAQs and exemplars. The present document is a document on core high-level principles (axioms) that will serve to motivate specific methodological recommendations, and it should be method-agnostic as much as possible.
It is fine, though, to mention specific methods and procedures as examples, using the "example:" format. Keep the examples very short and provide a reference if necessary.

__2. Focus on statistics.__ Do not include discussions that pertain to research methods or study design: this is about transparent statistics. Statistics are arguably tightly connected to study design, but we can discuss issues of study design in a separate FAQ and set of exemplars, if needed. Anything that pertains to statistical communication (e.g, how we frame conclusions, share material, etc) is however part of this document. 

__3. Focus on transparency.__ This document is not about getting our statistics right. The first principle "faithfulness" already states that our stats need to be correct, perhaps there is no need to elaborate more on this. The many ways we can get our stats wrong can be covered in much more depth in FAQs and exemplars.

__4. Justify.__ Add references as much as possible. Also justify using common sense and logics, especially when adding a new principle. The principle should be self-evident in a transparent statistics context, or should logically follow from other principles. Some redundancy in the document is OK, but avoid too much overlap between principles. Ask yourself if the new principle is really only a subset (or a superset) of existing principles.
